name: tencent_map
description: Tencent Map SDK for Flutter, support ios and android.
version: 0.5.0
homepage: https://github.com/qiuxiang/flutter-tencent-map

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: 5.0.1

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.tencent_map
        pluginClass: TencentMapPlugin
      ios:
        pluginClass: TencentMapPlugin
